---
title: "Overview Objects Implemented"
output: html_document
vignette: >
  %\VignetteIndexEntry{OverviewObjects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following RSMinerve objects are currently implemented in RSMinerveR:  
- Station  
- Source  
- SOCONT  
- Kinematic  
- Junction  
- GSM  
- Comparator  

The parameters for these objects are described in the RS Minerve User Manual available from the [CREALP website](https://www.crealp.ch/fr/accueil/outils-services/logiciels/rs-minerve/telechargement-rsm.html). The format of the parameter file is described below:  

## Parameter file
An example parameter file looks like the following: 

```
RS MINERVE - Parameters
Version 4.0.0.0 - vendredi 7 août 2015 09:20
Model: Z:\MEDIA\CREALP\Projets\64002-Mandat Laguna513 (Perou)\12 Formation RSM\Formation Linea de comando\Examples\Model.rsm
Description: Model
Database: 
OBJECTS
Comparator	1
GSM	1
Junction	3
Kinematic	2
SOCONT	3
Source	1
Station	4
VALUES
Comparator	Zone	
Comparador	A	
GSM	Zone	A (m2)	An (mm/°C/day)	ThetaCri (-)	bp (d/mm)	Tcp1 (°C)	Tcp2 (°C)	Tcf (°C)	Agl (mm/°C/day)	Tcg (°C)	Kgl (1/d)	Ksn (1/d)
GSM 1	A	28267674	7	0.1	0.0125	0	4	0	3	0	0.8	0.3
Junction	Zone	
Confluencia A	A	
Confluencia B	A	
Desembocadura	A	
Kinematic	Zone	L (m)	B0 (m)	m (-)	J0 (-)	K (m1/3/s)	N (-)
Río B	A	7558	4	1	0.0004	30	1
Rio A	A	6565	5	1	0.0001	30	1
SOCONT	Zone	A (m2)	An (mm/°C/day)	ThetaCri (-)	bp (d/mm)	Tcp1 (°C)	Tcp2 (°C)	Tcf (°C)	HGR3Max (m)	KGR3 (1/s)	L (m)	J0 (-)	Kr (m1/3/s)
SOCONT 1	A	48302423	8	0.1	0.0125	0	4	0	0.8	0.001	2500	0.01	2
SOCONT 2	A	38025778	8	0.1	0.0125	0	4	0	1	0.001	1500	0.01	2
SOCONT 3	A	52640259	8	0.1	0.0125	0	4	0	1	0.001	2000	0.01	3
Source	Zone	
Fuente	A	
Station	Zone	X (m)	Y (m)	Z (masl)	Search Radius (m)	No. min. of stations (-)	Gradient P (m/s/m)	Gradient T (C/m)	Gradient ETP (m/s/m)	Coeff P (-)	Coeff T (-)	Coeff ETP (-)
Estacion GSM 1	A	606636	108339	3025	10000	1	0	-0.0065	0	1	0	1
Estacion SOCONT 1	A	601667	107380	2889	10000	1	0	-0.0065	0	1	0	1
Estacion SOCONT 2	A	606291	101382	2406	10000	1	0	-0.0065	0	1	0	1
Estacion SOCONT 3	A	605067	95762	1947	10000	1	0	-0.0065	0	1	0	1
```
It includes 5 header lines describing the model. These are followed by a header OBJECTS which gives a list of the RS Minerve objects implemented in the model and the number of the objects. For each of the objects under OBJECTS, the parameter values are given under VALUES. Each object type is thereby preceded by a line describing the parameter names and units.  

Note that the units of the parameters in the parameter files do not always correspond to the units of the parameters in the RS MInerve user interface. 

## Comparator, Source, Junction
These objects contain only one parameter: the zone they are allocated to. Zone is parsed as a character string.  


## GSM	
The GSM parameters are: Zone, A (m2), An (mm/°C/day), ThetaCri (-), bp (d/mm), Tcp1 (°C), Tcp2 (°C), Tcf (°C), Agl (mm/°C/day), Tcg (°C), Kgl (1/d), Ksn (1/d).   
In RSMinerveR, the round brackets are replaced by [] and °C is replaced by deg C.  
Note that Zone is parsed as character and the other parameters as numeric. 


## SOCONT	
The SOCONT parameters are: Zone, A (m2), An (mm/°C/day), ThetaCri (-), bp (d/mm), Tcp1 (°C), Tcp2 (°C), Tcf (°C), HGR3Max (m), KGR3 (1/s), L (m), J0 (-), Kr (m1/3/s).   
In RSMinerveR, the round brackets are replaced by [] and °C is replaced by deg C.   
Note that Zone is parsed as character and the other parameters as numeric.   


## Kinematic	
The Kinematic wave parameters are Zone, L (m), B0 (m), m (-), J0 (-), K (m1/3/s), N (-).  
In RSMinerveR, the round brackets are replaced by [].   
Note that Zone is parsed as character and the other parameters as numeric. 


## Station	
The Station parameters are Zone, X (m), Y (m), Z (masl), Search Radius (m), No. min. of stations (-), Gradient P (m/s/m), Gradient T (C/m), Gradient ETP (m/s/m), Coeff P (-), Coeff T (-), Coeff ETP (-).    
In RSMinerveR, the round brackets are replaced by [] and °C is replaced by deg C.   
Note that Zone is parsed as character and the other parameters as numeric. 
